#!/bin/sh

set -e
exec 2>&1
set -u

cd "$AUTOPKGTEST_TMP"

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

echo "1..1"

cat > simple.c <<'EOF'
#include <glib-object.h>
#include <librsvg/rsvg.h>

int main (void)
{
    RsvgHandle *handle;

    handle = rsvg_handle_new ();
    g_object_unref (handle);

    g_print ("ok 1\n");
    return 0;
}
EOF

# Deliberately word-splitting, that's how pkg-config works:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -o simple simple.c $("${CROSS_COMPILE}pkg-config" --cflags --libs librsvg-2.0 gobject-2.0)
test -x simple
./simple
echo "# everything seems OK"
